import hashlib
import logging
import os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple, TYPE_CHECKING

import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup
from langchain_text_splitters import RecursiveCharacterTextSplitter

from .. import calibre_db, config

if TYPE_CHECKING:  # pragma: no cover - typing only import
    from .context_fuse import ContextFuser


log = logging.getLogger(__name__)


@dataclass
class Chunk:
    """
    Lightweight chunk representation before it is persisted to the database.
    """

    text: str
    book_id: int
    chunk_index: int
    chapter_index: int
    chapter_title: str
    chapter_id: str
    chunk_index_in_chapter: Optional[int] = None
    context_window: Optional[str] = None
    enriched_context: Optional[str] = None

    def __post_init__(self):
        cleaned = self.text.strip()
        if not cleaned:
            raise ValueError("Chunk text cannot be empty")
        self.text = cleaned
        self.word_count = len(cleaned.split())
        self.char_count = len(cleaned)

    @property
    def chunk_hash(self) -> str:
        return hashlib.sha256(self.text.encode("utf-8")).hexdigest()

    def to_rag_row(self) -> Dict[str, Any]:
        return {
            "hash_id": f"chunk-{self.book_id}-{self.chunk_index}",
            "content": self.text,
            "order_index": self.chunk_index,
            "chapter_id": self.chapter_id,
            "chapter_index": self.chapter_index,
            "chapter_title": self.chapter_title,
            "chunk_index_in_chapter": self.chunk_index_in_chapter,
            "word_count": self.word_count,
            "char_count": self.char_count,
        }


class BookParser:
    """
    Parse an EPUB file into discrete chunks for RAG indexing.
    """

    def __init__(
        self,
        chunk_size: int = 800,
        chunk_overlap: int = 200,
        enable_contextual: bool = False,
        context_neighbors: int = 2,
        max_context_chars: int = 2000,
        fuse_batch_size: int = 8,
        context_fuser: Optional["ContextFuser"] = None,
    ):
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.enable_contextual = enable_contextual
        self.context_neighbors = max(0, context_neighbors)
        self.max_context_chars = max_context_chars if max_context_chars > 0 else 2000
        self.fuse_batch_size = max(1, fuse_batch_size)
        self.context_fuser = context_fuser if enable_contextual else None
        if self.enable_contextual and self.context_fuser is None:
            self.context_fuser = self._build_context_fuser()
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            separators=["\n\n", "\n", "。", "！", "？", "，", " ", ""],
        )

    def chunk_book(self, book_id: int, file_path: Optional[str] = None) -> List[str]:
        """
        Given a book id (and optionally an explicit file path), split the EPUB contents
        into chunks. When contextual mode is enabled, each chunk will carry a
        `context_window` (neighboring text) and an `enriched_context` string
        generated by `ContextFuser`.

        Returns:
            List of generated ver hash_ids.
        """
        epub_path = file_path or self._resolve_book_path(book_id)
        if not epub_path:
            raise ValueError("Book file path is required to chunk content")

        book = epub.read_epub(epub_path)
        chapter_docs = self._extract_chapters(book)
        chunks = self._chunk_chapters(book_id, chapter_docs)
        return [chunk.to_rag_row()["hash_id"] for chunk in chunks]

    def _extract_chapters(self, book) -> List[dict]:
        chapters = []
        for item in book.get_items():
            if item.get_type() != ebooklib.ITEM_DOCUMENT:
                continue
            soup = BeautifulSoup(item.get_content(), "html.parser")
            text = soup.get_text("\n", strip=True)
            if not text:
                continue
            chapters.append(
                {
                    "id": item.get_id() or item.get_name(),
                    "index": len(chapters),
                    "title": self._guess_title(soup, len(chapters)),
                    "text": text,
                }
            )
        return chapters

    def _chunk_chapters(self, book_id: int, chapters: List[dict]) -> List[Chunk]:
        chunks: List[Chunk] = []
        chunk_index = 0
        fuse_inputs: List[Tuple[str, str, Chunk]] = []

        for chapter in chapters:
            pieces = self.text_splitter.split_text(chapter["text"])
            start_idx = len(chunks)
            for piece in pieces:
                cleaned = piece.strip()
                if not cleaned:
                    continue
                chunks.append(
                    Chunk(
                        text=cleaned,
                        book_id=book_id,
                        chunk_index=chunk_index,
                        chapter_index=chapter["index"],
                        chapter_title=chapter["title"],
                        chapter_id=str(chapter["id"]),
                    )
                )
                chunk_index += 1

            end_idx = len(chunks)
            chapter_chunks = chunks[start_idx:end_idx]
            if not chapter_chunks:
                continue
            for chapter_offset, chapter_chunk in enumerate(chapter_chunks):
                chapter_chunk.chunk_index_in_chapter = chapter_offset
            self._attach_context_windows(chapter_chunks)
            if self.enable_contextual and self.context_fuser:
                for chapter_chunk in chapter_chunks:
                    doc_source = chapter_chunk.context_window or chapter_chunk.text
                    fuse_inputs.append((doc_source, chapter_chunk.text, chapter_chunk))

        if self.enable_contextual and self.context_fuser and fuse_inputs:
            self._enrich_chunks_with_fused_context(fuse_inputs)

        return chunks

    def _attach_context_windows(self, chapter_chunks: Sequence[Chunk]) -> None:
        if not chapter_chunks:
            return
        total = len(chapter_chunks)
        for idx, chunk in enumerate(chapter_chunks):
            start = max(0, idx - self.context_neighbors)
            end = min(total, idx + self.context_neighbors + 1)
            window = "\n\n".join(chapter_chunks[i].text for i in range(start, end))
            chunk.context_window = self._trim_context_window(window)

    def _trim_context_window(self, window: str) -> str:
        trimmed = window.strip()
        if not trimmed or len(trimmed) <= self.max_context_chars:
            return trimmed
        cutoff = trimmed.rfind("\n", 0, self.max_context_chars)
        if cutoff == -1:
            cutoff = self.max_context_chars
        return trimmed[:cutoff].rstrip()

    def _enrich_chunks_with_fused_context(
        self, fuse_inputs: Sequence[Tuple[str, str, Chunk]]
    ) -> None:
        if not self.context_fuser:
            return
        doc_chunk_pairs = [(doc, chunk_text) for doc, chunk_text, _ in fuse_inputs]
        fused_outputs = self.context_fuser.batch_fuse(
            doc_chunk_pairs, batch_size=self.fuse_batch_size
        )
        if len(fused_outputs) != len(fuse_inputs):
            log.warning(
                "Fused output length mismatch. expected=%s actual=%s",
                len(fuse_inputs),
                len(fused_outputs),
            )
        for (_doc, _chunk_text, chunk), enriched in zip(fuse_inputs, fused_outputs):
            chunk.enriched_context = enriched or None

    def _build_context_fuser(self) -> "ContextFuser":
        from .context_fuse import ContextFuser

        return ContextFuser()

    @staticmethod
    def _guess_title(soup: BeautifulSoup, fallback_index: int) -> str:
        for selector in ("h1", "h2", "h3", "title"):
            node = soup.find(selector)
            if node and node.get_text(strip=True):
                return node.get_text(strip=True)
        return f"Chapter {fallback_index + 1}"

    @staticmethod
    def _resolve_book_path(book_id: int) -> Optional[str]:
        """
        Placeholder for mapping a Calibre book_id to the actual file path.
        Implementers should override or extend this method.
        """
        book = calibre_db.get_book(book_id)

        if not book:
            return None

        readable_formats = ["epub", "kepub", "txt"]
        book_format = None
        book_data = None

        for data in book.data:
            if data.format.lower() in readable_formats:
                book_format = data.format.lower()
                book_data = data
                break

        if not book_format:
            return None

        file_path = os.path.normpath(
            os.path.join(config.config_calibre_dir, book.path, book_data.name + "." + book_format)
        )

        if not os.path.exists(file_path):
            return None

        return file_path
